config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'archives/index'
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "تمت الإضافة" }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "تم التعديل" }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "تم الحذف" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:appartment, :flat, :name, :phone, :join, :durat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<h1>Archives#index</h1>
<p>Find me in app/views/archives/index.html.erb</p>

app/views/entries/_entry.html.erb
  <div  id="<%= dom_id entry %>">
    <p>
      <strong>المبنى:</strong>
      <%= entry.appartment %>
    </p>

    <p>
      <strong>رقم الشقة:</strong>
      <%= entry.flat %>
    </p>

    <p>
      <strong>اسم المستأجر:</strong>
      <%= entry.name %>
    </p>

    <p>
      <strong>رقم الجوال:</strong>
      <%= entry.phone %>
    </p>

    <p>
      <strong>موعد الدخول:</strong>
      <%= entry.join %>
    </p>

    <p>
      <strong>المدة:</strong>
      <%= entry.duration %>
    </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="form-group">
    <%= form.text_field :appartment, class:"form-control", placeholder:"المبنى" %>
  </div>

  <div class="form-group">
    <%= form.text_field :flat, class:"form-control", placeholder:"رقم الشقة" %>
  </div>

  <div class="form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"اسم المستأجر" %>
  </div>

  <div class="form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"رقم الجوال" %>
  </div>

 <div class="form-group">
    <%= form.text_field :join, class:"form-control", placeholder:"موعد الدخول" %>
 </div>

  <div class="form-group">
    <%= form.text_field :duration, class:"form-control", placeholder:"المدة" %>
 </div>


  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1 style="text-align: right;">تعديل</h1>

<%= render "form", entry: @entry %>


<div >
  <%= link_to "الرئيسية", entries_path, class:"btn btn-primary" %>
</div>

app/views/entries/index.html.erb
<p style="color: green" ><%= notice %></p>

<h1 style="text-align: right;">الشقق</h1>
<div class="card" style="width: 18rem;" class="layout-right">
  <div class="card-body" style="text-align: right;">
    <div id="entries">
      <% @entries.each do |entry| %>
        <%= render entry %>
         <% if user_signed_in? %>
          <p>
            <%= link_to "إظهار", entry, class:"btn btn-success" %> 
          </p>
        <% end %>
        <hr><br>
      <% end %>
    </div>
  </div>
</div>

app/views/entries/new.html.erb
<h1 style="text-align: right;">إضافة</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "الرئيسية", entries_path, class:"btn btn-primary" %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>
<div style="text-align: right;">
  <%= render @entry %>
</div>

<div style="text-align: right;">
  <%= link_to "تعديل", edit_entry_path(@entry), class:"btn btn-info" %> <br><br>
  
  
  <br><br>
  <%= button_to "حذف", @entry, method: :delete, class:"btn btn-danger" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar fixed-buttom navbar-expand-lg navbar-light bg-light" >

       <div>
               
                <% if user_signed_in? %>
                        <%= link_to "الرئيسية", root_path, class:"btn btn-outline-primary" %> 
                        <%= link_to "إضافة", new_entry_path, class:"btn btn-outline-primary btn-sm" %>  
                        <%= link_to "تعديل الحساب ", edit_user_registration_path, class:"btn btn-outline-primary btn-sm" %>

                <% else %>
                        <%= link_to "تسجيل الدخول", new_user_session_path, class:"btn btn-outline-primary btn-sm" %>  <br>
                
                <% end %>
        </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE >
<html dir="rtl" style="text-align: right;" >
  <head>
    <title>App</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render 'home/header' %>

    <div  class="container">

      <%= yield %>
    </div>
  </body>
</html>